name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:lts-community
        options: --name sonarqube -p 9080:9080
        ports:
          - 9080:9080

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Run Sonar Scanner
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=http://172.17.0.4:9080 \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v $GITHUB_WORKSPACE:/usr/src \
            sonarsource/sonar-scanner-cli
