name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution you want, e.g., 'adopt', 'adopt-openj9', 'adopt-hotspot', etc.
        architecture: 'x64'
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Install certificates
      run: |
        # Install your certificate to the system trust store
        # Replace <your-cert-file.crt> with the actual certificate file
         sudo cp 92a37fbd5e21a53a95c716e1144f442f582b94d0fafc673eb6717a4eb51a88a7 /usr/local/share/ca-certificates/
         sudo update-ca-certificates

    - name: Run SonarQube analysis
      run: |
        # Use the SonarScanner to analyze your code
        # Replace <your-sonar-server-ip> with the actual IP address of your Sonar server
        sonar-scanner \
          -Dsonar.host.url=http://192.168.0.17:9000 \
          -Dsonar.login=squ_fcd51069e8f0f1e4838f37df32fd564c2cd4a860

    - name: Upload SonarQube analysis results
      uses: actions/upload-artifact@v2
      with:
        name: sonarqube-report
        path: .scannerwork
