jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: sonarqube:latest
      options: --http://192.168.0.17:9100
    steps:
      - name: Check SonarQube
        run: |
          # Your commands to access SonarQube here
