name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access SonarQube
      run: |
        # Make an HTTP request to access SonarQube
        curl -I http://192.168.0.17:9000
